server:
  port: 8091

spring:
  application:
    name: course
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/course_service_db
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true